package it.polimi.se2018.view.gui;

public enum State {
    WAIT_MOVE,
    NOT_YOUR_TURN,
    INCREMENT_REQUEST,
    COORDINATES_REQUEST,
    VALID_REQUEST,
    DP_INDEX_REQUEST,
    RT_POSITION_REQUEST,
    NEW_VALUE_REQUEST;
}
